version: '3.9'

services:
  app:
    container_name: springboot_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: mysql
    networks:
      - mysql-network

  mysql:
    container_name: mysql_host
    image: mysql:8.0.27
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mysql
    restart: always
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge
